name: Make sure PRs are targeted to `develop`.

on:
  pull_request_target:
    types: [opened]
   
jobs:
  check-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: Vankka/pr-target-branch-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: develop
          change-to: develop
          comment: |
            Your PR was set to target `main`, but it should be directed to `develop`. The base branch has been updated to `develop`, please check for any merge conflicts.
